# verbose = true

[front]
host = "0.0.0.0"
port = 8080

[[back]]
type = "static"
path = "/public"
dir  = "/var/www/html"
# autoindex   = true
remove_path = true

[[back]]
path = "/ch"
port = 8123
remove_path = true

[[back]]
path = "/"
port = 9001

[logger]
path  = "STDOUT" # "STDOUT", "STDERR", "/tmp/run.log"
mode  = "w+"     # "w+", "a+"
level = "INFO"   # "DEBUG", "INFO", "WARN", "ERROR", "FATAL"
# colorize = true